#ifndef HQRP_CONSTANTS_H
#define HQRP_CONSTANTS_H

#define HQRP_SCREEN_WIDTH 320
#define HQRP_SCREEN_HEIGHT 240

#define PORT_DATA GPIOC
#define PIN_DATA_0 GPIO_PIN_0
#define PIN_DATA_1 GPIO_PIN_1
#define PIN_DATA_2 GPIO_PIN_2
#define PIN_DATA_3 GPIO_PIN_3
#define PIN_DATA_4 GPIO_PIN_4
#define PIN_DATA_5 GPIO_PIN_5
#define PIN_DATA_6 GPIO_PIN_6
#define PIN_DATA_7 GPIO_PIN_7
#define PIN_DATA_8 GPIO_PIN_8
#define PIN_DATA_9 GPIO_PIN_9

#define PORT_DATA_10 GPIOA
#define PIN_DATA_10 GPIO_PIN_0
#define PORT_DATA_11 GPIOA
#define PIN_DATA_11 GPIO_PIN_1
#define PORT_DATA_12 GPIOA
#define PIN_DATA_12 GPIO_PIN_4

#define PORT_DATA_13 GPIOB
#define PIN_DATA_13 GPIO_PIN_8
#define PORT_DATA_14 GPIOB
#define PIN_DATA_14 GPIO_PIN_9
#define PORT_DATA_15 GPIOA
#define PIN_DATA_15 GPIO_PIN_8

#define PORT_LCD_CS GPIOA
#define PIN_LCD_CS GPIO_PIN_12
#define PORT_WR GPIOA
#define PIN_WR GPIO_PIN_11

#define PORT_RST GPIOB
#define PIN_RST GPIO_PIN_12
#define PORT_BL_CTRL GPIOB
#define PIN_BL_CTRL GPIO_PIN_11
#define PORT_RS GPIOB
#define PIN_RS GPIO_PIN_15
#define PORT_RD GPIOB
#define PIN_RD GPIO_PIN_14
#define PORT_NC GPIOB
#define PIN_NC GPIO_PIN_13

#define PORT_TP_CS GPIOB
#define PIN_TP_CS GPIO_PIN_6
#define PORT_TP_SDI GPIOC
#define PIN_TP_SDI GPIO_PIN_12
#define PORT_TP_IRQ GPIOB
#define PIN_TP_IRQ GPIO_PIN_10
#define PORT_TP_SCK GPIOC
#define PIN_TP_SCK GPIO_PIN_10
#define PORT_TP_SDO GPIOC
#define PIN_TP_SDO GPIO_PIN_11

#define HQRP_COLOUR_TRANSPARENT 0

#define HQRP_COLOUR_BLACK 1
#define HQRP_COLOUR_GRAY 3152
#define HQRP_COLOUR_WHITE 0xFFFF

#define HQRP_COLOUR_BLUE 500
#define HQRP_COLOUR_NAVY 200
#define HQRP_COLOUR_ARCTIC 1200

#define HQRP_COLOUR_GREEN 4000
#define HQRP_COLOUR_PEAR 800
#define HQRP_COLOUR_SEAFOAM 1000

#define HQRP_COLOUR_RED 64000
#define HQRP_COLOUR_PINK 64019

#define HQRP_COLOUR_YELLOW 65376
#define HQRP_COLOUR_ORANGE 64900
#define HQRP_COLOUR_BROWN 16641

#define HQRP_FONT_CHAR_COUNT 41
#define HQRP_FONT_CHAR_WIDTH 3
#define HQRP_FONT_CHAR_HEIGHT 5
#define HQRP_FONT_CHAR_SIZE HQRP_FONT_CHAR_WIDTH * HQRP_FONT_CHAR_HEIGHT

#endif