#ifndef HQRPGE_CONSTANTS_H
#define HQRPGE_CONSTANTS_H

#include <hqrp_constants.h>

#define HQRPGE_GFX_SCALE 5
#define HQRPGE_SPRITE_WIDTH 8
#define HQRPGE_SPRITE_HEIGHT 8
#define HQRPGE_SPRITE_SIZE                        \
	(HQRP_Vec2) {                                 \
		HQRPGE_SPRITE_WIDTH, HQRPGE_SPRITE_HEIGHT \
	}

#define HQRPGE_SPRITE_POKE_WIDTH 16
#define HQRPGE_SPRITE_POKE_HEIGHT 18
#define HQRPGE_SPRITE_POKE_SIZE                             \
	(HQRP_Vec2) {                                           \
		HQRPGE_SPRITE_POKE_WIDTH, HQRPGE_SPRITE_POKE_HEIGHT \
	}

#define HQRPGE_MAP_VIEW_WIDTH 5
#define HQRPGE_MAP_VIEW_HEIGHT 5

#define HQRPGE_MINIMAP_WALL_COLOUR HQRP_COLOUR_BLACK
#define HQRPGE_MINIMAP_FLOOR_COLOUR HQRP_COLOUR_PEAR
#define HQRPGE_MINIMAP_PLAYER_COLOUR HQRP_COLOUR_RED
#define HQRPGE_MINIMAP_ENEMY_COLOUR HQRP_COLOUR_PINK

#define HQRPGE_WEAPON_NAME_LENGTH 16
#define HQRPGE_POKE_NAME_LENGTH 16

#define HQRPGE_FLOOR_ID 1
#define HQRPGE_WALL_ID 0
#define HQRPGE_ROOM_ID 2

#define HQRPGE_MAX_ENTITES 8
#define HQRPGE_STARTER_POKES_COUNT 3
#define HQRPGE_AVAILABLE_POKES 3

#define HQRPGE_ENEMY_SPAWN_RATE 20

#define HQRPGE_MAP_SIZE 40
#define HQRPGE_MAP_MAX_ROOMS 10

#define HQRPGE_GUI_DIALOGBOX_BUTTONS_MAX 3
#define HQRPGE_GUI_DIALOGBOX_TEXT_LENGTH_MAX 128
#define HQRPGE_GUI_BUTTON_TEXT_LENGTH_MAX 16

#endif